default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: weekly_workshop

development:
  <<: *default
  database: active_resource_dev

test:
  <<: *default
  database: active_resource_test

production:
  <<: *default
  database: active_resource_prod
